// AUTO-GENERATED by prepare-certificates.mjs — do not edit by hand.
export type OtherCertificate = { title: string; file: string; type: 'image' | 'pdf' }

export const otherCertificates: OtherCertificate[] = [
  {
    "title": "COEPED BA Course",
    "file": "/certificates/COEPED_BA_Course.jpeg",
    "type": "image"
  },
  {
    "title": "Credentials Siddharthaborpuzari 9992 Microsoft Learn",
    "file": "/certificates/Credentials_-_siddharthaborpuzari-9992___Microsoft_Learn.PDF",
    "type": "pdf"
  },
  {
    "title": "Digital Image Processing",
    "file": "/certificates/Digital_Image_Processing.pdf",
    "type": "pdf"
  },
  {
    "title": "MS Excel",
    "file": "/certificates/MS_Excel.pdf",
    "type": "pdf"
  },
  {
    "title": "Six Sigma Certificate",
    "file": "/certificates/Six_Sigma_certificate.jpeg",
    "type": "image"
  }
]
